from pefc.geom import CadPt, Entity, Point, Line, Circle, Arc

# TODO: port this over to pytest

print('*** Test results compared to ./data/geom tests.dwg ***')
print('\nCadPt Tests')
cpt0 = CadPt()
print(cpt0)
cpt = CadPt(5.0, 9.0)
print(cpt)
print('repr =', repr(cpt))  # dataclasses already have a __repr__
cpt.position = (-10.0, 28.5)
print(cpt)
print('cpt =', cpt.position)
print('*** class methods test ***')
cpt1 = CadPt.from_tuple((23.75, 32.25))
print('cpt1 =', repr(cpt1))
cpt_1 = CadPt.from_cadpt(cpt)
print('cpt_1 =', repr(cpt_1))
cpt2 = CadPt(180.3, 650.5)
cpt = cpt2
print(cpt)
print('del cpt.position:')
del cpt.position
print(cpt)
cpt1 = CadPt(1.0, 5.0)
cpt2 = CadPt(2.5, 1.5)
print('cpt1 =', cpt1.position)
print('cpt2 =', cpt2.position)
print('dist  =', cpt1.distance_to(cpt2))
print('angle =', cpt1.angle(cpt2))
print('*** static methods test ***')
print('dist  =', CadPt.distance_between_pts(*cpt1.position, *cpt2.position))
print('angle =', CadPt.angle_of_line(*cpt1.position, *cpt2.position))

print('\nEntity Tests')
ent = Entity()
print(ent)
print('repr =', repr(ent))
print(ent.properties)

print('\nPoint Tests')
pt0 = Point()  # test default
print(pt0)
pt1 = Point(CadPt(20.5, 32.8), clr='blue')
print(pt1)
print('repr =', repr(pt1))
print(pt1.properties)
x, y = pt1.position
print('Point pt1 Coordinates:', x, y)
print(f'{pt1}, {repr(pt1)}')
cpt3 = CadPt(-98.7, -75.5)
pt1.pt_position = cpt3
print('pt1 =', pt1)
print('pt1 properties:', pt1.properties)
pt2 = Point(CadPt(16.875, 93.836), 'green', '1', 'dashed')
print('pt2 properties:', pt2.properties)
pt3 = Point(CadPt(11.33, 88.75), clr='yellow', lyr='plan')
print('pt3 properties:', pt3.properties)
print('dist =', pt2.distance_to(pt3))

print('\nLine Tests')
ln0 = Line()
print(ln0)
ln1 = Line(CadPt(3.0, 5.0), CadPt(10.0, 15.5), lyr='side view')
print(ln1)
print('repr =', repr(ln1))
print(ln1.properties)
print('ln1 length =', ln1.length())
print('ln1 angle  =', ln1.angle())
ln2 = Line(CadPt(7.0, 5.0), CadPt(3.0, 15.0))
print('ln2 length =', ln2.length())
print('ln2 angle  =', ln2.angle())
print('ln1 degenerate?', ln1.is_degenerate())
ln3 = Line(CadPt(7.0, 5.0), CadPt(7.0, 5.0))
print('ln3 (start point=end point) degenerate?', ln3.is_degenerate())

print('\nCircle Tests')
cir0 = Circle()
print(cir0)
cir1 = Circle(CadPt(9, 8), 5.25, ltype='hidden')
print(cir1)
print('repr =', repr(cir1))
print(cir1.properties)
print('radius        =', cir1.radius)
print('diameter      =', cir1.diameter)
print('area          =', cir1.area)
print('circumference =', cir1.circumference)
cir2 = Circle(CadPt(-4.0, 12.0), 2.5)
print('dist =', cir1.distance_to(cir2))
print('cir1 degenerate?', cir1.is_degenerate())
cir3 = Circle(CadPt(-5.0, 16.0), 0.0)
print('cir3 (radius = 0.0) degenerate?', cir3.is_degenerate())
cir3.diameter = 50
print('cir3 with new diameter of 50:')
print(cir3)

print('\nArc Tests')
arc0 = Arc()
print(arc0)
arc1 = Arc(CadPt(15, 9), 3.75, 25, 200, clr='red', lyr='front view')
print(arc1)
print('repr =', repr(arc1))
print('Arc1 ccw whose end_angle > start_angle example:')
print(arc1.properties)
print('radius        =', arc1.radius)
print('diameter      =', arc1.diameter)
print('start angle   =', arc1.start_angle)
print('end angle     =', arc1.end_angle)
print('swept angle   =', arc1.sweep_angle)
print('length        =', arc1.length)
print('area          =', arc1.area)
arc2 = Arc(CadPt(15, 9), 3.75, 200.0, 25.0)
print('Arc2 ccw whose end_angle <= start_angle example:')
print(arc2)
print('radius        =', arc2.radius)
print('diameter      =', arc2.diameter)
print('start angle   =', arc2.start_angle)
print('end angle     =', arc2.end_angle)
print('swept angle   =', arc2.sweep_angle)
print('length        =', arc2.length)
print('area          =', arc2.area)
print('Arc3 cw whose end_angle > start_angle example:')
arc3 = Arc(CadPt(25, 12.5), 5.0, 0.0, 260.0, True)
print(arc3)
print('radius        =', arc3.radius)
print('diameter      =', arc3.diameter)
print('start angle   =', arc3.start_angle)
print('end angle     =', arc3.end_angle)
print('swept angle   =', arc3.sweep_angle)
print('length        =', arc3.length)
print('area          =', arc3.area)
print('Arc4 cw whose end_angle <= start_angle example:')
arc4 = Arc(CadPt(25, 12.5), 5.0, 260.0, 0.0, True)
print(arc4)
print('radius        =', arc4.radius)
print('diameter      =', arc4.diameter)
print('start angle   =', arc4.start_angle)
print('end angle     =', arc4.end_angle)
print('swept angle   =', arc4.sweep_angle)
print('length        =', arc4.length)
print('area          =', arc4.area)
print('Arc4 cw whose end_angle >= start_angle example:')
arc5 = Arc(CadPt(37.0, 3.0), 5.0, 260.0, 350.0, True)
print(arc5)
print('radius        =', arc5.radius)
print('diameter      =', arc5.diameter)
print('start angle   =', arc5.start_angle)
print('end angle     =', arc5.end_angle)
print('swept angle   =', arc5.sweep_angle)
print('length        =', arc5.length)
print('area          =', arc5.area)
print('arc5 degenerate?', arc5.is_degenerate())
arc6 = Arc(CadPt(37.0, 3.0), 0.0, 260.0, 350.0, True)
print('arc6 degenerate for radius = 0.0?', arc6.is_degenerate())
arc6 = Arc(CadPt(37.0, 3.0), 5.0, 260.0, 260.0, True)
print('arc6 degenerate for start_angle=end_angle?', arc6.is_degenerate())
